apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: email-microservice
  name: email-microservice
  namespace: development
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: email-microservice
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75