apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailmicroservice
  namespace: deployment
  labels:
    app: user-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emailmicroservice
  template:
    metadata:
      labels:
        app: emailmicroservice
    spec:
      containers:
        - name: emailmicroservice
          image: joeriberman/email-microservice
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /ready
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
          livenessProbe:
            httpGet:
              path: /healthy
              port: 80
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 15
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 64Mi