apiVersion: v1
kind: Service
metadata:
  labels:
    app: email-service
  name: email-service
  namespace: development
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: email-service
  type: ClusterIP